# Generated by Django 5.0.4 on 2024-07-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='cause',
            field=models.TextField(default='Unknown cause'),
        ),
        migrations.AddField(
            model_name='disease',
            name='precaution',
            field=models.TextField(default='No specific precaution'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='disease',
            name='medicines',
            field=models.ManyToManyField(blank=True, to='diseases.medicine'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
